SLOT_LEN = 12.0

SEED = 6
P_SEND = 0.2

SLOT_START = "SLOT_START"
SLOT_END   = "SLOT_END"
SEND_TX    = "SEND_TX"
TX_ARRIVE  = "TX_ARRIVE"
USER_TICK  = "USER_TICK"
BUILDER_TICK = "BUILDER_TICK"

N_SLOTS = 2
N_USERS = 3
USER_TICK = 0.5
N_BUILDERS = 1
BUILDER_TICK = 3
N_VALIDATORS = 1